name: rashed
description: "Flutter App for Graudation Project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  meta: ^1.15.0
  bloc: ^8.1.4
  flutter_bloc: ^8.0.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_screenutil: ^5.9.0
  dio: ^5.4.0
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.4
  intl: ^0.20.2
  flutter_spinkit: ^5.2.0
  awesome_dialog:
    git:
      url: https://github.com/A7mdlbanna/awesomeDialogs.git
  shimmer: ^3.0.0
  flutter_markdown: ^0.7.5
  path_provider: ^2.1.5
  http: ^1.3.0
  socket_io_client: ^3.1.2
  share_plus: ^11.0.0
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  flutter_tts: ^4.2.3
  file_picker: ^10.2.0
  pdf: ^3.11.3
  read_pdf_text: ^0.3.1
  open_filex: ^4.7.0
  device_info_plus: ^11.5.0
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/